name: Create Archives
on: [push]
jobs:
  archive-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest
        run: |
          git config --global user.name "OakLoaf"
          git config --global user.email "${{ secrets.EMAIL }}"
          git config pull.rebase false
          git pull
          mkdir -p output/bedrock

      - name: Remove old outputs
        run: |
          rm -f output/release.zip
          rm -f output/adjusted_bedrock.zip

      - name: Archive java
        run: |
          cd pack
          zip -r ../output/release.zip ./*
          cd ..

      - name: Replace model files
        run: |
          cp -r bedrock_overrides/* pack/

      - name: Archive adjusted bedrock
        run: |
          cd pack
          zip -r ../output/adjusted_bedrock.zip ./*
          cd ..

      - name: Install dependencies
        run: |
          sudo apt-get install -y moreutils zip
          yarn global add spritesheet-js

      - name: Convert bedrock pack
        run: |
          mkdir -p converting
          cp converter.sh converting/
          cd converting
          chmod +x converter.sh
          ./converter.sh ../output/adjusted_bedrock.zip -r "true"
          cp target/packaged/geyser_resources.mcpack ../output/bedrock/pack.mcpack
          cp target/geyser_mappings.json ../output/bedrock/geyser_mappings.json
          cd..

      - name: Push archives
        run: |
          git add output/release.zip
          git add output/adjusted_bedrock.zip
          git add output/Pack Files.zip
          git commit -m "Updated release.zip" -- output/release.zip
          git commit -m "Updated adjusted_bedrock.zip" -- output/adjusted_bedrock.zip
          git commit -m "Updated adjusted_bedrock.zip" -- output/adjusted_bedrock.zip
          git push --force
